/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package splashscreen;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author GilangMF
 */
public class load extends javax.swing.JFrame {

    /**
     * Creates new form load
     */
    public load() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("logo.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroudPanel = new javax.swing.JPanel();
        BackGroundLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LoadingValue = new javax.swing.JLabel();
        LoadingLabel = new javax.swing.JLabel();
        LoadingBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        BackgroudPanel.setBackground(new java.awt.Color(51, 166, 200));
        BackgroudPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackGroundLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/splashscreen/LogoDepan.png"))); // NOI18N
        BackgroudPanel.add(BackGroundLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 200, 170));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Cambria", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("StegoCrypt");
        BackgroudPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 250, 70));

        LoadingValue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LoadingValue.setForeground(new java.awt.Color(255, 255, 255));
        LoadingValue.setText("0%");
        BackgroudPanel.add(LoadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, -1, -1));

        LoadingLabel.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        LoadingLabel.setForeground(new java.awt.Color(204, 204, 204));
        LoadingLabel.setText("Loading..");
        BackgroudPanel.add(LoadingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));
        BackgroudPanel.add(LoadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 340, 610, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackgroudPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroudPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 356, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            
        load sp = new load();
        sp.setVisible(true);
        
        try {
            for (int i=0; i<=100; i++) {
                Thread.sleep(100);
                sp.LoadingValue.setText(i + "%");
                
                if(i==10) {
                    sp.LoadingLabel.setText("Turning On Modules..");
                }
                if(i==20) {
                    sp.LoadingLabel.setText("Loading Modules..");
                }
                if(i==50) {
                    sp.LoadingLabel.setText("Connecting to localhost..");
                }
                if(i==70) {
                    sp.LoadingLabel.setText("Please Wait.. ");
                }
                if(i==85) {
                    sp.LoadingLabel.setText("Ready to Open..");
                }
                if(i==95) {
                    sp.LoadingLabel.setText("Application Open..");
                }
                if(i==100) {
                    sp.dispose();
                }
                sp.LoadingBar.setValue(i);
                
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            
        }
        appstegano.Stegano_view app = new appstegano.Stegano_view();
        app.setVisible(true);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGroundLogo;
    private javax.swing.JPanel BackgroudPanel;
    private javax.swing.JProgressBar LoadingBar;
    private javax.swing.JLabel LoadingLabel;
    private javax.swing.JLabel LoadingValue;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
